config/routes.rb
Rails.application.routes.draw do
  devise_for :costumers
  resources :deliveryinfos
  resources :ingpizzas
  resources :ingredients
  resources :recipes
  resources :orderpizzas
  resources :crusts
  resources :pizzas
  resources :orders
  resources :customers

  root 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/crust.rb
class Crust < ApplicationRecord
  belongs_to :pizza
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :phone, :address1, :address2, presence: true
  validates :phone, numericality: {only_integer: true}


end

app/models/ingpizza.rb
class Ingpizza < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingpizza
  has_many :recipes, :through => :ingpizza
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :pizzas, :through => :orderpizza

end

app/models/orderpizza.rb
class Orderpizza < ApplicationRecord
  belongs_to :pizza
  belongs_to :order

  validates :pizza, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :recipe
  has_many :orderpizzas, :through => :orderpizzas
  has_one :crust
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :pizza
  has_many :ingpizzas
  has_many :ingredients, :through => :ingpizzas

end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:type, :price, :pizza_id)
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :recipe_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveryinfos_helper.rb
module DeliveryinfosHelper
end

app/helpers/ingpizzas_helper.rb
module IngpizzasHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orderpizzas_helper.rb
module OrderpizzasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, local: true) do |form| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

  </div>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.number_field :recipe_id %>

  </div>
  <div class="field">
    <%= form.label :crust_id %>
    <%= form.number_field :crust_id %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzas</h1>

<button id="myBtn" data-toggle="modal" class= "btn btn-succes" data-target="#myModal">Generate a Cart</button>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2>Pizza</h2>
    </div>
    <div class="modal-body">
      <%= form_for Order.new do |f|%>
        <% if costumer_signed_in? %>
            <%= f.hidden_field :customer_id, :value => current_costumer.id %>
         <%else%>
            <%= f.hidden_field :customer_id, :value => 1%>
          <%end%>

        </div>
        <div class="modal-footer">
          <%= f.submit "Generate a Cart", class: "btn btn-primary"%>
      <% end %>
      </div>
      <div class="modal-footer">
        <h3></h3>
      </div>
      </div>

</div>

</div>

<div class="row">
  <% @pizzas.each do |pizza| %>

      <div class="col-sm-4">
          <%=link_to pizza.name, pizza_path(pizza) %>
        <br>
        <br>





    </div>
  <%end%>
</div>





    <br>

<%= link_to 'New Pizza', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%=@pizza.name%></h1>



<br>



<br>

<button id="myBtn" data-toggle="modal" class= "btn btn-success" data-target="#myModal<%=@pizza.id %>">Add to Cart</button>

<!-- The Modal -->
<div id="myModal<%=@pizza.id %>" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2>Pizza</h2>
    </div>
    <div class="modal-body">
      <%= form_for Orderpizza.new do |f|%>

        <%= f.hidden_field :order_id, :value => 1 %>
        <%= f.hidden_field :pizza_id, :value => @pizza.id %>
        <%= f.label :payment %>
        <%= f.text_field :payment %>

        </div>
        <div class="modal-footer">
          <%= f.submit "Add to cart", class: "btn btn-primary"%>
      <% end %>
      </div>
      <div class="modal-footer">
        <h3></h3>
      </div>
      </div>

</div>

<button id="myBtn" data-toggle="modal" class= "btn btn-success" data-target="#myModal1">Choose Crust</button>

<!-- The Modal -->
<div id="myModal1" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2>Pizza</h2>
    </div>
    <div class="modal-body">
      <%= form_for Crust.new do |f|%>

        <%= f.hidden_field :pizza_id, :value => @pizza.id %>
        <%= f.label :type %>
        <%= f.text_field :type %>
        <%= f.hidden_field :price, :value => 1 %>

        </div>
        <div class="modal-footer">
          <%= f.submit "Choose crust", class: "btn btn-primary"%>
      <% end %>
      </div>
      <div class="modal-footer">
        <h3></h3>
      </div>
      </div>

</div>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>