config/routes.rb
Rails.application.routes.draw do
  devise_for :costumers
  resources :deliveryinfos
  resources :ingpizzas
  resources :ingredients
  resources :recipes
  resources :orderpizzas
  resources :crusts
  resources :pizzas
  resources :orders
  resources :customers

  root 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/crust.rb
class Crust < ApplicationRecord
  belongs_to :pizza
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :phone, :address1, :address2, presence: true
  validates :phone, numericality: {only_integer: true}


end

app/models/ingpizza.rb
class Ingpizza < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingpizza
  has_many :recipes, :through => :ingpizza
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :pizzas, :through => :orderpizza

end

app/models/orderpizza.rb
class Orderpizza < ApplicationRecord
  belongs_to :pizza
  belongs_to :order

  validates :pizza, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :recipe
  has_many :orderpizzas, :through => :orderpizzas
  has_one :crust
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :pizza
  has_many :ingpizzas
  has_many :ingredients, :through => :ingpizzas

end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:type, :price, :pizza_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveryinfos_helper.rb
module DeliveryinfosHelper
end

app/helpers/ingpizzas_helper.rb
module IngpizzasHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orderpizzas_helper.rb
module OrderpizzasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/crusts/_form.html.erb
<%= form_with(model: crust, local: true) do |form| %>
  <% if crust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crust.errors.count, "error") %> prohibited this crust from being saved:</h2>

      <ul>
      <% crust.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :crust_type %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :crust_price %>
  </div>

  <div class="field">
    <%= form.label :pizza_id %>
    <%= form.text_field :pizza_id, id: :crust_pizza_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crusts/edit.html.erb
<h1>Editing Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Show', @crust %> |
<%= link_to 'Back', crusts_path %>

app/views/crusts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crusts</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Price</th>
      <th>Pizza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crusts.each do |crust| %>
      <tr>
        <td><%= crust.typeofcrust %></td>
        <td><%= crust.price %></td>
        <td><%= crust.pizza %></td>
        <td><%= link_to 'Show', crust %></td>
        <td><%= link_to 'Edit', edit_crust_path(crust) %></td>
        <td><%= link_to 'Destroy', crust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crust', new_crust_path %>

app/views/crusts/new.html.erb
<h1>New Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Back', crusts_path %>

app/views/crusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @crust.type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @crust.price %>
</p>

<p>
  <strong>Pizza:</strong>
  <%= @crust.pizza %>
</p>

<%= link_to 'Edit', edit_crust_path(@crust) %> |
<%= link_to 'Back', crusts_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, id: :order_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer.id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer %>
</p>



<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>