config/routes.rb
Rails.application.routes.draw do
  devise_for :costumers
  resources :deliveryinfos
  resources :ingpizzas
  resources :ingredients
  resources :recipes
  resources :orderpizzas
  resources :crusts
  resources :pizzas
  resources :orders
  resources :customers

  root 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/crust.rb
class Crust < ApplicationRecord
  belongs_to :pizza
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :phone, :address1, :address2, presence: true
  validates :phone, numericality: {only_integer: true}


end

app/models/ingpizza.rb
class Ingpizza < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingpizza
  has_many :recipes, :through => :ingpizza
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :pizzas, :through => :orderpizza

end

app/models/orderpizza.rb
class Orderpizza < ApplicationRecord
  belongs_to :pizza
  belongs_to :order

  validates :pizza, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :recipe
  has_many :orderpizzas, :through => :orderpizzas
  has_one :crust
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :pizza
  has_many :ingpizzas
  has_many :ingredients, :through => :ingpizzas

end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:type, :price, :pizza_id)
    end
end

app/controllers/orderpizzas_controller.rb
class OrderpizzasController < ApplicationController
  before_action :set_orderpizza, only: [:show, :edit, :update, :destroy]

  # GET /orderpizzas
  # GET /orderpizzas.json
  def index
    @orderpizzas = Orderpizza.all
  end

  # GET /orderpizzas/1
  # GET /orderpizzas/1.json
  def show
  end

  # GET /orderpizzas/new
  def new
    @orderpizza = Orderpizza.new
  end

  # GET /orderpizzas/1/edit
  def edit
  end

  # POST /orderpizzas
  # POST /orderpizzas.json
  def create
    @orderpizza = Orderpizza.new(orderpizza_params)

    respond_to do |format|
      if @orderpizza.save
        format.html { redirect_to @orderpizza, notice: 'Orderpizza was successfully created.' }
        format.json { render :show, status: :created, location: @orderpizza }
      else
        format.html { render :new }
        format.json { render json: @orderpizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderpizzas/1
  # PATCH/PUT /orderpizzas/1.json
  def update
    respond_to do |format|
      if @orderpizza.update(orderpizza_params)
        format.html { redirect_to @orderpizza, notice: 'Orderpizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderpizza }
      else
        format.html { render :edit }
        format.json { render json: @orderpizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderpizzas/1
  # DELETE /orderpizzas/1.json
  def destroy
    @orderpizza.destroy
    respond_to do |format|
      format.html { redirect_to orderpizzas_url, notice: 'Orderpizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderpizza
      @orderpizza = Orderpizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderpizza_params
      params.require(:orderpizza).permit(:payment, :pizza_id, :order_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveryinfos_helper.rb
module DeliveryinfosHelper
end

app/helpers/ingpizzas_helper.rb
module IngpizzasHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orderpizzas_helper.rb
module OrderpizzasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/orderpizzas/_form.html.erb
<%= form_with(model: orderpizza, local: true) do |form| %>
  <% if orderpizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orderpizza.errors.count, "error") %> prohibited this orderpizza from being saved:</h2>

      <ul>
      <% orderpizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payment %>
    <%= form.text_field :payment, id: :orderpizza_payment %>
  </div>

  <div class="field">
    <%= form.label :pizza_id %>
    <%= form.text_field :pizza_id, id: :orderpizza_pizza_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, id: :orderpizza_order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orderpizzas/edit.html.erb
<h1>Editing Orderpizza</h1>

<%= render 'form', orderpizza: @orderpizza %>

<%= link_to 'Show', @orderpizza %> |
<%= link_to 'Back', orderpizzas_path %>

app/views/orderpizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping cart</h1>

<table>
  <thead>
    <tr>
      <th>Payment</th>
      <th colspan="3"></th>
      <th>Pizza</th>
      <th colspan="3"></th>
      <th>Customer id</th>
      <th colspan="3"></th>
      <th>Recipe:</th>
    </tr>
  </thead>

  <tbody>
    <% @orderpizzas.each do |orderpizza| %>
      <tr>
        <td><%= orderpizza.payment %></td>
        <th colspan="3"></th>
        <td><%= link_to orderpizza.pizza.name, pizza_path(orderpizza.pizza) %></td>
        <th colspan="3"></th>
        <td><%= orderpizza.order.customer_id %></td>
        <th colspan="3"></th>
        <% link_to orderpizza.pizza.recipe_id, recipes_path%>
        <th colspan="3"></th>
        <td><%= link_to 'Show', orderpizza %></td>
        <td><%= link_to 'Destroy', orderpizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<button id="myBtn" data-toggle="modal" class= "btn btn-success" data-target="#myModal<%=@pizza %>">Buy</button>

<!-- The Modal -->
<div id="myModal<%=@pizza %>" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2>Buy</h2>
    </div>
    <div class="modal-body">
      <%= form_for Deliveryinfo.new do |f|%>

        <%= f.hidden_field :order_id, :value => 1 %>
        <%= f.label :address1 %>
        <%= f.text_field :address1 %>
        <%= f.label :address2 %>
        <%= f.text_field :address2 %>
        <%= f.label :phone %>
        <%= f.number_field :phone %>

        </div>
        <div class="modal-footer">
          <%= f.submit "Confirm", class: "btn btn-primary"%>
      <% end %>
      </div>
      <div class="modal-footer">
        <h3></h3>
      </div>
      </div>

</div>

<br>

<%= link_to 'New Orderpizza', new_orderpizza_path %>

app/views/orderpizzas/new.html.erb
<h1>New Orderpizza</h1>

<%= render 'form', orderpizza: @orderpizza %>

<%= link_to 'Back', orderpizzas_path %>

app/views/orderpizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment:</strong>
  <%= @orderpizza.payment %>
</p>

<p>
  <strong>Pizza:</strong>
  <%= @orderpizza.pizza %>
</p>

<p>
  <strong>Order:</strong>
  <%= @orderpizza.order %>
</p>

<%= link_to 'Edit', edit_orderpizza_path(@orderpizza) %> |
<%= link_to 'Back', orderpizzas_path %>