config/routes.rb
Rails.application.routes.draw do
  devise_for :costumers
  resources :deliveryinfos
  resources :ingpizzas
  resources :ingredients
  resources :recipes
  resources :orderpizzas
  resources :crusts
  resources :pizzas
  resources :orders
  resources :customers

  root 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/crust.rb
class Crust < ApplicationRecord
  belongs_to :pizza
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :phone, :address1, :address2, presence: true
  validates :phone, numericality: {only_integer: true}


end

app/models/ingpizza.rb
class Ingpizza < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingpizza
  has_many :recipes, :through => :ingpizza
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :pizzas, :through => :orderpizza

end

app/models/orderpizza.rb
class Orderpizza < ApplicationRecord
  belongs_to :pizza
  belongs_to :order

  validates :pizza, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :recipe
  has_many :orderpizzas, :through => :orderpizzas
  has_one :crust
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one :pizza
  has_many :ingpizzas
  has_many :ingredients, :through => :ingpizzas

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/ingpizzas_helper.rb
module IngpizzasHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orderpizzas_helper.rb
module OrderpizzasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<!DOCTYPE html>
<html>
  <head>
    <title>ExamCaroassadi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-md  bg-dark navbar-dark fixed-top" >
      <!-- Brand -->
      <a class="navbar-brand" href="/">Joe's Pizza</a>

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <%= link_to 'Cart', orderpizzas_path %>
        </ul>
        <ul class="navbar-nav ml-auto">
        <% if costumer_signed_in? %>
          <%= link_to 'Log Out', destroy_costumer_session_path, :method => :delete %>
          <%else%>
          <%= link_to '| Log In |   ', new_costumer_session_path %>
          <%= link_to 'Sign Up |', new_costumer_registration_path %>
          <% end %>
        </ul>

      </div>
    </nav>
  </header>


    <%= yield %>
  </body>
</html>